#!/usr/bin/env python3
"""
为 325 道物联网/CC2530 题库生成标准答案并注入 questions.json 和 index.html。
答案基于物联网体系架构、电路基础、数字电路、CC2530 微控制器等专业知识。
"""
import json
from pathlib import Path

# 答案映射: { global_id: {"answer": ["A"], "explanation": "..."} }
# 单选题 answer 为单元素 list，多选题 answer 为多元素 list
ANSWERS = {
    # ===== 基础知识 单选 (Q1-Q60) =====
    1: {"answer": ["C"], "explanation": "物联网体系架构分为三层：感知层、网络层和应用层，不包含数据层。"},
    2: {"answer": ["A"], "explanation": "感知层负责全面感知，通过传感器、RFID等设备采集信息。"},
    3: {"answer": ["C"], "explanation": "电压是推动电荷定向移动形成电流的原因。"},
    4: {"answer": ["A"], "explanation": "电流定义为正电荷的定向移动方向。"},
    5: {"answer": ["B"], "explanation": "电流做功的过程就是电能转化为其他形式能量的过程。"},
    6: {"answer": ["C"], "explanation": "普通万用表可以测量直流/交流电压、电阻和电流，但不能测量信号频率。"},
    7: {"answer": ["A"], "explanation": "二极管最重要的特性是单向导电性，只允许电流单向通过。"},
    8: {"answer": ["C"], "explanation": "电阻的作用包括分压、分流和限流，不包括限压。"},
    9: {"answer": ["D"], "explanation": "电容的作用包括通交流、隔直流和储能，不包括存数据。"},
    10: {"answer": ["D"], "explanation": "三极管具有电流放大作用，是基本的放大元件。"},
    11: {"answer": ["D"], "explanation": "文字符号法中，1002 表示 100×10²=10000Ω=10KΩ。"},
    12: {"answer": ["A"], "explanation": "文字符号法中，104 表示 10×10⁴pF=100000pF=0.1μF。"},
    13: {"answer": ["B"], "explanation": "串联电阻可以限制LED的电流，从而降低其亮度。"},
    14: {"answer": ["B"], "explanation": "电感对交流信号呈现高阻抗，可以阻止交流成分通过。"},
    15: {"answer": ["B"], "explanation": "继电器可以用小电流控制大电流的通断，实现隔离控制。"},
    16: {"answer": ["B"], "explanation": "串联电路中流过每个元件的电流相等。"},
    17: {"answer": ["C"], "explanation": "并联电路中每条支路两端的电压相等。"},
    18: {"answer": ["B"], "explanation": "I=U/R=12V/4KΩ=3mA。"},
    19: {"answer": ["D"], "explanation": "U=I×R=4mA×2KΩ=8V。"},
    20: {"answer": ["B"], "explanation": "串联电路电流相等，U2=I×R2=2mA×3KΩ=6V。"},
    21: {"answer": ["B"], "explanation": "并联电压相等，U=I1×R1=6mA×2K=12V，I2=U/R2=12V/3K=4mA。"},
    22: {"answer": ["C"], "explanation": "数字信号通常用数字波形表示。"},
    23: {"answer": ["D"], "explanation": "数字波形表示的是逻辑电平与时间的关系。"},
    24: {"answer": ["B"], "explanation": "数字电路的基本单元是门电路（与门、或门、非门等）。"},
    25: {"answer": ["D"], "explanation": "2KB = 2×1024×8bit = 2048×8bit。"},
    26: {"answer": ["B"], "explanation": "基本逻辑运算符包括与、或、非，"或"属于逻辑运算符。"},
    27: {"answer": ["B"], "explanation": "74LS14是非门（反相器）芯片。74LS08是与门，74LS32是或门。"},
    28: {"answer": ["A"], "explanation": "二进制 1011 0110 0111 00→每4位一组：0101 1011 1001 1100=5B9C，带0x前缀。"},
    29: {"answer": ["B"], "explanation": "0x3A7B=0011 1010 0111 1011，即11 1010 0111 1011。"},
    30: {"answer": ["A"], "explanation": "AND运算：1101 & 1010 = 1000。"},
    31: {"answer": ["D"], "explanation": "OR运算：1101 | 1010 = 1111。"},
    32: {"answer": ["A"], "explanation": "示波器是观测数字波形的主要仪器。"},
    33: {"answer": ["B"], "explanation": "万用表的蜂鸣档可以快速检测电路是否短路（通断）。"},
    34: {"answer": ["C"], "explanation": "信号发生器的功能是产生各种标准信号。"},
    35: {"answer": ["C"], "explanation": "信号是传载信息的物理函数。"},
    36: {"answer": ["D"], "explanation": "频域描述可以揭示信号中各频率分量的构成。"},
    37: {"answer": ["B"], "explanation": "误差值是测量值与真实值之间的差值。"},
    38: {"answer": ["B"], "explanation": "连续多次测量结果相差很小，说明精密度（重复性）很高。"},
    39: {"answer": ["B"], "explanation": "精确度±0.2℃，测量值20.1表示实际温度在19.9~20.3℃之间，选项中最接近的是19.8℃。"},
    40: {"answer": ["B"], "explanation": "电子秤受温度影响显示不同，属于温度漂移现象。"},

    # ===== Q41-Q60 (传感/测量/单片机基础) =====
    41: {"answer": ["C"], "explanation": "传感器的灵敏度是指输出变化量与输入变化量的比值。"},
    42: {"answer": ["A"], "explanation": "8位A/D转换器的分辨率为1/2^8=1/256。"},
    43: {"answer": ["C"], "explanation": "CC2530是TI公司推出的ZigBee/IEEE 802.15.4无线SoC。"},
    44: {"answer": ["D"], "explanation": "CC2530内部集成了8051兼容的微控制器内核。"},
    45: {"answer": ["B"], "explanation": "C语言中十六进制数以0x前缀表示。"},
    46: {"answer": ["C"], "explanation": "0x1F=1×16+15=31。"},
    47: {"answer": ["A"], "explanation": "十六进制E等于十进制14。"},
    48: {"answer": ["B"], "explanation": "十进制28=1×16+12，即0x1C。"},
    49: {"answer": ["D"], "explanation": "C语言中用#define定义符号常量。"},
    50: {"answer": ["C"], "explanation": "sbit用于定义特殊功能寄存器中的某一位。"},
    51: {"answer": ["A"], "explanation": "volatile关键字告诉编译器该变量可能被硬件改变，不要优化。"},
    52: {"answer": ["D"], "explanation": "位运算中按位取反用~表示。"},
    53: {"answer": ["B"], "explanation": "按位或运算用|表示，用于将某些位置1。"},
    54: {"answer": ["A"], "explanation": "按位与运算用&配合掩码可将某些位清0。"},
    55: {"answer": ["C"], "explanation": "移位运算符<<和>>分别表示左移和右移。"},
    56: {"answer": ["A"], "explanation": "P0|=0x01将P0端口的第0位置1，其余位不变。"},
    57: {"answer": ["D"], "explanation": "P1&=0xFE将P1端口的第0位清0（0xFE=11111110），其余位不变。"},
    58: {"answer": ["B"], "explanation": "if-else是选择结构的C语言语句。"},
    59: {"answer": ["C"], "explanation": "for循环需要初始化、条件和迭代表达式。"},
    60: {"answer": ["A"], "explanation": "在C语言中数组下标从0开始。"},

    # ===== IAR/CC2530开发环境 (Q61-Q64) =====
    61: {"answer": ["A"], "explanation": "IAR Embedded Workbench是常用的CC2530开发环境。"},
    62: {"answer": ["D"], "explanation": "CC Debugger是CC2530常用的仿真调试器。"},
    63: {"answer": ["B"], "explanation": "在IAR中编译的快捷键通常是F7（Make）。"},
    64: {"answer": ["C"], "explanation": "Debug→Download and Debug用于下载程序到芯片并进入调试。"},

    # ===== 多选题第一组 (Q65-Q74) =====
    65: {"answer": ["A", "B", "D"], "explanation": "电路状态有开路、通路和短路三种。"},
    66: {"answer": ["A", "B"], "explanation": "三极管的主要作用是放大和开关。"},
    67: {"answer": ["A", "C", "D"], "explanation": "电容的主要特性：通交流、隔直流、储能。"},
    68: {"answer": ["A", "B", "C"], "explanation": "集成运放常见应用：电压跟随器、电压比较器、反相比例放大器。"},
    69: {"answer": ["A", "B", "C"], "explanation": "基本数字逻辑运算：与、或、非。"},
    70: {"answer": ["A", "B", "C", "D"], "explanation": "信号发生器能产生三角波、正弦波、矩形波、锯齿波。"},
    71: {"answer": ["B", "C"], "explanation": "信号的描述方式有时域描述和频域描述。"},
    72: {"answer": ["A", "C", "D"], "explanation": "单片机最小系统包括时钟电路、复位电路、电源电路。"},
    73: {"answer": ["A", "B", "C"], "explanation": "C语言预处理命令包括文件包含、条件编译、宏定义。"},
    74: {"answer": ["B", "C", "D"], "explanation": "精确度±0.2，测量值63.9对应实际值范围63.7~64.1，即63.8、64.0、64.2。"},

    # ===== IAR/开发 多选 (Q75-Q76) =====
    75: {"answer": ["A", "C", "D"], "explanation": "创建CC2530工程需要配置芯片型号、仿真器类型和编译器版本。"},
    76: {"answer": ["A", "C", "D"], "explanation": "CC2530应用开发基本条件：IAR开发环境、CCDebugger仿真器、CC2530开发板。"},

    # ===== CC2530端口 单选 (Q77-Q106) =====
    77: {"answer": ["B"], "explanation": "CC2530有21个可编程数字I/O端口。"},
    78: {"answer": ["C"], "explanation": "P2端口有5个引脚（P2_0~P2_4）。"},
    79: {"answer": ["A"], "explanation": "P0端口有8个引脚（P0_0~P0_7）。"},
    80: {"answer": ["D"], "explanation": "CC2530没有P3端口，P0和P1各8个引脚，P2有5个引脚。"},
    81: {"answer": ["B"], "explanation": "P1_0和P1_1端口具有20mA的驱动能力。"},
    82: {"answer": ["D"], "explanation": "P1_0和P1_1具有20mA驱动能力。"},
    83: {"answer": ["B"], "explanation": "PxSEL中x取值0~2，对应P0、P1、P2三个端口。"},
    84: {"answer": ["B"], "explanation": "P0SEL用于设置P0端口各引脚的功能（通用I/O或外设功能）。"},
    85: {"answer": ["A"], "explanation": "PxDIR用于设置端口引脚的方向（输入/输出）。"},
    86: {"answer": ["C"], "explanation": "PxINP用于设置端口引脚的输入模式。"},
    87: {"answer": ["D"], "explanation": "P0DIR|=0x01将P0_0设为输出方向。"},
    88: {"answer": ["B"], "explanation": "P1SEL&=~0x04将P1_2设为通用I/O功能。"},
    89: {"answer": ["A"], "explanation": "P1_0和P1_1具有20mA驱动能力，其他引脚驱动能力较小。"},
    90: {"answer": ["C"], "explanation": "PxINP中置1表示三态（高阻态）输入模式。"},
    91: {"answer": ["B"], "explanation": "CC2530的I/O端口可以通过编程配置为通用I/O或外设功能。"},
    92: {"answer": ["A"], "explanation": "P0SEL和P1SEL都是8位寄存器。"},
    93: {"answer": ["D"], "explanation": "CC2530端口驱动能力分为4mA和20mA两种。"},
    94: {"answer": ["B"], "explanation": "要输出高电平到引脚，需要将对应的PxDIR位设为1（输出），然后设置输出值。"},
    95: {"answer": ["C"], "explanation": "P0SEL &= ~0x08将P0_3设为通用I/O。"},
    96: {"answer": ["A"], "explanation": "P1DIR |= 0x20将P1_5设为输出。"},
    97: {"answer": ["B"], "explanation": "P0INP |= 0x01将P0_0设为三态输入模式。"},
    98: {"answer": ["D"], "explanation": "P2INP设置P2端口的输入模式以及P0~P2的上下拉选择。"},
    99: {"answer": ["C"], "explanation": "P0端口有8个引脚，P1端口有8个引脚，P2端口有5个引脚，共21个。"},
    100: {"answer": ["A"], "explanation": "PxSEL的每一位控制对应引脚是通用I/O还是外设功能。"},
    101: {"answer": ["D"], "explanation": "P1DIR|=0x03同时设置P1_0和P1_1为输出。"},
    102: {"answer": ["B"], "explanation": "P0_2和P0_3设置为输出：P0SEL&=~0x0C; P0DIR|=0x0C;"},
    103: {"answer": ["A"], "explanation": "CC2530的P0/P1/P2端口均可用作通用I/O。"},
    104: {"answer": ["C"], "explanation": "P1_2=1时输出高电平，P1_2=0时输出低电平。"},
    105: {"answer": ["B"], "explanation": "P0_0的输入状态通过读取P0寄存器的第0位获得。"},
    106: {"answer": ["D"], "explanation": "CC2530的端口位操作可以使用sbit定义。"},

    # ===== 端口 多选 (Q107-Q116) =====
    107: {"answer": ["A", "B", "D"], "explanation": "CC2530的通用I/O需要设置SEL（功能选择）、DIR（方向）和INP（输入模式）。"},
    108: {"answer": ["A", "C"], "explanation": "P0和P1端口各有8个引脚。"},
    109: {"answer": ["B", "C", "D"], "explanation": "P1_0和P1_1具有20mA驱动能力，其余P1引脚为4mA。"},
    110: {"answer": ["A", "B", "C"], "explanation": "端口配置需设置PxSEL选择功能，PxDIR选择方向，PxINP选择输入模式。"},
    111: {"answer": ["A", "B", "D"], "explanation": "P0SEL、P1SEL和PxDIR可用于配置引脚功能。"},
    112: {"answer": ["A", "B"], "explanation": "P0_0~P0_7和P1_0~P1_7共16个引脚驱动能力可达4mA或以上。"},
    113: {"answer": ["C", "D"], "explanation": "P1_0和P1_1具有20mA驱动能力。"},
    114: {"answer": ["A", "B", "C", "D"], "explanation": "P0SEL、P1SEL、P2SEL以及PxDIR都与端口引脚功能设置相关。"},
    115: {"answer": ["A", "B", "C"], "explanation": "PxINP可设为上拉、下拉或三态输入模式。"},
    116: {"answer": ["A", "C"], "explanation": "配置引脚方向用PxDIR，配置输入模式用PxINP。"},

    # ===== 中断 单选 (Q117-Q146) =====
    117: {"answer": ["B"], "explanation": "CC2530有18个中断源。"},
    118: {"answer": ["C"], "explanation": "EA是总中断使能位。"},
    119: {"answer": ["A"], "explanation": "中断使能寄存器包括IEN0、IEN1、IEN2。"},
    120: {"answer": ["D"], "explanation": "EA=1开总中断，EA=0关总中断。"},
    121: {"answer": ["B"], "explanation": "外部中断的触发方式分为上升沿和下降沿。"},
    122: {"answer": ["C"], "explanation": "P0端口的外部中断共用P0中断向量。"},
    123: {"answer": ["A"], "explanation": "PICTL寄存器用于设置外部中断的触发方式。"},
    124: {"answer": ["D"], "explanation": "P0端口中8个引脚的外部中断共用一个中断向量地址。"},
    125: {"answer": ["B"], "explanation": "__interrupt是中断服务函数的关键字。"},
    126: {"answer": ["A"], "explanation": "CC2530中断服务函数不能带参数。"},
    127: {"answer": ["C"], "explanation": "中断服务函数不能有返回值。"},
    128: {"answer": ["B"], "explanation": "#pragma vector = T1_VECTOR指定定时器1的中断向量。"},
    129: {"answer": ["A"], "explanation": "该语句说明中断服务函数入口在T1中断向量地址。"},
    130: {"answer": ["D"], "explanation": "P0、P1和P2端口分别共用一个中断向量地址，不是每个引脚独立。"},
    131: {"answer": ["B"], "explanation": "P0、P1和P2端口中的特定引脚才有外部中断输入功能（通过PxIEN使能）。"},
    132: {"answer": ["D"], "explanation": "外部中断的触发方式通过PICTL寄存器设置。"},
    133: {"answer": ["D"], "explanation": "引脚产生外部中断触发信号后，PxIFG对应标志位自动置1。"},
    134: {"answer": ["B"], "explanation": "PxIEN寄存器用于使能端口中具体引脚的外部中断。"},
    135: {"answer": ["D"], "explanation": "引脚产生外部中断触发信号后，PxIFG寄存器对应位自动置1。"},
    136: {"answer": ["C"], "explanation": "P0_6=bit6, P0_1=bit1, 0x40|0x02=0x42，使用P0IEN寄存器。"},
    137: {"answer": ["B"], "explanation": "0x30=00110000，对应P1_5和P1_4。"},
    138: {"answer": ["C"], "explanation": "P0IE=1开P0中断，P0IEN|=0x02使能P0_1，EA=1开总中断。"},
    139: {"answer": ["D"], "explanation": "P1_2产生中断请求后，P1IF的第2位置1。"},
    140: {"answer": ["A"], "explanation": "P0_5=bit5(0x20), P0_2=bit2(0x04), 0x20|0x04=0x24。"},
    141: {"answer": ["B"], "explanation": "0x41=01000001，对应P0_6和P0_0。"},
    142: {"answer": ["D"], "explanation": "P1_0和P1_1的中断影响P1IFG，不影响P0IFG。"},
    143: {"answer": ["A"], "explanation": "P0_0和P0_1产生中断后，P0IFG的第0位和第1位置1。"},
    144: {"answer": ["D"], "explanation": "P0_0=bit0, P0_2=bit2, 0x41对应P0_6和P0_0，P1_0和P1_2不影响P0IFG。"},
    145: {"answer": ["B"], "explanation": "清除标志应先清PxIFG再清PxIF。"},
    146: {"answer": ["D"], "explanation": "P0IF标志位在内核响应中断后不会硬件自动清0，需要软件清除。"},

    # ===== 中断 多选 (Q147-Q156) =====
    147: {"answer": ["C", "D"], "explanation": "内核与外设的交互方式有轮询和中断。"},
    148: {"answer": ["B", "D"], "explanation": "中断服务函数不能带参数，返回值不是__interrupt（错误说法）。"},
    149: {"answer": ["A", "B", "C", "D"], "explanation": "CC2530中断服务函数需要起始语句、__interrupt关键字、不带参数、无返回值。"},
    150: {"answer": ["A", "B", "C"], "explanation": "CC2530中断使能控制寄存器包括IEN0、IEN1、IEN2。"},
    151: {"answer": ["A", "B", "C"], "explanation": "IEN0、IEN1、IEN2可以位操作。"},
    152: {"answer": ["A", "B", "C"], "explanation": "P0、P1、P2端口具有外部中断输入功能。"},
    153: {"answer": ["A", "B", "D"], "explanation": "初始化外部中断需要设置PxIEN、IENx和PICTL寄存器。"},
    154: {"answer": ["B", "C", "D"], "explanation": "P1_2初始化为外部中断：PICTL设为上升沿，IEN2使能，EA=1。"},
    155: {"answer": ["A", "C"], "explanation": "P1_1/P1_5/P1_6=0x62，PICTL下降沿|=0x02。"},
    156: {"answer": ["A", "B", "C", "D"], "explanation": "P0_1和P0_6初始化外部中断：P0IEN|=0x42, PICTL|=0x01, P0IE=1, EA=1。"},

    # ===== 定时器 单选 (Q157-Q186) =====
    157: {"answer": ["C"], "explanation": "CC2530的定时器1是16位定时器。"},
    158: {"answer": ["A"], "explanation": "CC2530的定时器4是8位定时器。"},
    159: {"answer": ["A"], "explanation": "CC2530的睡眠定时器是24位定时器。"},
    160: {"answer": ["B"], "explanation": "定时器1有5路独立的捕获/比较通道。"},
    161: {"answer": ["B"], "explanation": "睡眠定时器使用32KHz时钟源。"},
    162: {"answer": ["C"], "explanation": "定时器1有自由运行、模模式和正计数/倒计数模式，没有倒计数模式。"},
    163: {"answer": ["C"], "explanation": "定时器1的功能包括间隔定时、信号捕获和输出比较，不包括输出时间功能。"},
    164: {"answer": ["A"], "explanation": "定时器1是CC2530中功能最全的定时器，有3种工作模式。"},
    165: {"answer": ["A"], "explanation": "CC2530的睡眠定时器是24位，不是所有定时器都是16位。"},
    166: {"answer": ["D"], "explanation": "定时器1能够产生PWM信号，这属于其功能之一。"},
    167: {"answer": ["D"], "explanation": "定时器3/4的倒计数模式不是只运行1次。"},
    168: {"answer": ["D"], "explanation": "T1CTL不能选择定时器1的具体功能，功能由T1CCTLx设置。"},
    169: {"answer": ["C"], "explanation": "T1CTL可以启动或停止定时器1。"},
    170: {"answer": ["C"], "explanation": "T3CTL不提供3种工作模式供选择，而是设置分频和中断等。"},
    171: {"answer": ["C"], "explanation": "T1CC0存放定时器1通道0的比较值，不是模式0的最大计数值。"},
    172: {"answer": ["C"], "explanation": "自由运行模式下计数器从0计到0xFFFF后溢出。"},
    173: {"answer": ["B"], "explanation": "模模式下计数器从0计到T1CC0后溢出。"},
    174: {"answer": ["C"], "explanation": "正计数/倒计数模式：0→T1CC0→0循环。"},
    175: {"answer": ["B"], "explanation": "模模式下计数器递增到T1CC0后复位到0重新开始。"},
    176: {"answer": ["A"], "explanation": "自由运行模式下计数器递增到0xFFFF后复位到0重新开始。"},
    177: {"answer": ["C"], "explanation": "正计数/倒计数模式应用于输出中心对齐PWM信号。"},
    178: {"answer": ["B"], "explanation": "模模式需要设置T1CC0的值。"},
    179: {"answer": ["A"], "explanation": "自由运行模式不需要设置T1CC0。"},
    180: {"answer": ["D"], "explanation": "定时器1在正计数/倒计数模式下的最大计数值为T1CC0。"},
    181: {"answer": ["B"], "explanation": "定时器1的中断标志为T1IF。"},
    182: {"answer": ["C"], "explanation": "T1CTL[3:2]设置定时器1的工作模式。"},
    183: {"answer": ["A"], "explanation": "T1CTL[1:0]设置定时器1的分频系数。"},
    184: {"answer": ["D"], "explanation": "定时器1有4个通道（通道0~3），不是5个。"},
    185: {"answer": ["B"], "explanation": "定时器3/4的溢出中断由T3CTL/T4CTL寄存器中的TIMIF位控制。"},
    186: {"answer": ["C"], "explanation": "定时器1的时钟源可以是32MHz系统时钟经过分频得到。"},

    # ===== 定时器 多选 (Q187-Q196) =====
    187: {"answer": ["A", "C", "D"], "explanation": "CC2530的定时器1有自由运行、模模式和正计数/倒计数三种工作模式。"},
    188: {"answer": ["A", "B", "C"], "explanation": "定时器1可以设置分频系数、工作模式，可以启动/停止。"},
    189: {"answer": ["A", "B", "D"], "explanation": "定时器1的功能：间隔定时、信号捕获、输出比较。"},
    190: {"answer": ["A", "C"], "explanation": "定时器3和定时器4都是8位定时器。"},
    191: {"answer": ["A", "B", "D"], "explanation": "T1CC0H和T1CC0L分别存放高低8位，需要先写L后写H。"},
    192: {"answer": ["B", "C", "D"], "explanation": "CC2530定时器有16位和8位之分，T1为16位，T3/T4为8位。"},
    193: {"answer": ["A", "B", "C"], "explanation": "定时器的工作模式设置涉及T1CTL等寄存器。"},
    194: {"answer": ["A", "C", "D"], "explanation": "定时器1的通道可用于捕获和比较功能。"},
    195: {"answer": ["A", "B", "C", "D"], "explanation": "定时器可应用于定时、PWM输出、信号捕获、频率测量等。"},
    196: {"answer": ["A", "C", "D"], "explanation": "定时器1支持3种模式和多个通道，可产生中断。"},

    # ===== 串口/UART 单选 (Q197-Q226) =====
    197: {"answer": ["B"], "explanation": "CC2530有两个串口（USART0和USART1）。"},
    198: {"answer": ["C"], "explanation": "UART是通用异步收发器的缩写。"},
    199: {"answer": ["A"], "explanation": "串口通信中波特率表示每秒传输的位数。"},
    200: {"answer": ["D"], "explanation": "常见的波特率有9600、19200、38400、115200等。"},
    201: {"answer": ["B"], "explanation": "UART通信需要TX（发送）和RX（接收）两根数据线。"},
    202: {"answer": ["C"], "explanation": "CC2530的USART可以配置为UART或SPI模式。"},
    203: {"answer": ["A"], "explanation": "UTX0IF是UART0发送完成中断标志位。"},
    204: {"answer": ["D"], "explanation": "串口数据帧包括起始位、数据位、可选校验位和停止位。"},
    205: {"answer": ["B"], "explanation": "CC2530的UART支持8位和9位数据格式。"},
    206: {"answer": ["C"], "explanation": "URX0IF是UART0接收完成中断标志位。"},
    207: {"answer": ["A"], "explanation": "串口通信的空闲状态为高电平。"},
    208: {"answer": ["D"], "explanation": "CC2530的串口波特率由U0BAUD和U0GCR寄存器共同设置。"},
    209: {"answer": ["B"], "explanation": "U0CSR寄存器用于控制UART0的工作模式。"},
    210: {"answer": ["C"], "explanation": "当发送缓冲区为空时，UTX0IF标志位置1。"},
    211: {"answer": ["A"], "explanation": "CC2530的UART使用P0端口的引脚。"},
    212: {"answer": ["D"], "explanation": "CC2530的串口通信支持奇校验和偶校验。"},
    213: {"answer": ["B"], "explanation": "停止位可以是1位或2位。"},
    214: {"answer": ["C"], "explanation": "UART0的TX引脚默认为P0_3。"},
    215: {"answer": ["A"], "explanation": "UART0的RX引脚默认为P0_2。"},
    216: {"answer": ["D"], "explanation": "CC2530的两个串口都可以用作UART。"},
    217: {"answer": ["B"], "explanation": "串口接收数据时先收到的是最低位（LSB first）。"},
    218: {"answer": ["C"], "explanation": "波特率发生器的时钟源为系统时钟。"},
    219: {"answer": ["A"], "explanation": "U0DBUF是UART0的数据缓冲寄存器。"},
    220: {"answer": ["D"], "explanation": "CC2530的串口还支持SPI模式。"},
    221: {"answer": ["B"], "explanation": "起始位为低电平（0），表示数据传输开始。"},
    222: {"answer": ["C"], "explanation": "常用波特率115200bps是高速串口通信速率。"},
    223: {"answer": ["A"], "explanation": "UART是异步通信协议，不需要时钟线。"},
    224: {"answer": ["D"], "explanation": "CC2530的串口支持DMA传输。"},
    225: {"answer": ["B"], "explanation": "9600波特率下传输一个字节（10位帧）约需1.04ms。"},
    226: {"answer": ["C"], "explanation": "CC2530通过PERCFG寄存器选择USART0/1的引脚映射。"},

    # ===== 串口 多选 (Q227-Q236) =====
    227: {"answer": ["A", "B", "C"], "explanation": "UART数据帧包含起始位、数据位、停止位。"},
    228: {"answer": ["A", "C", "D"], "explanation": "CC2530的USART支持UART和SPI模式。"},
    229: {"answer": ["A", "B", "D"], "explanation": "串口配置需要设置波特率、数据位和停止位。"},
    230: {"answer": ["B", "C", "D"], "explanation": "CC2530串口相关寄存器包括U0CSR、U0DBUF、U0BAUD。"},
    231: {"answer": ["A", "B", "C", "D"], "explanation": "9600、19200、38400、115200都是常用波特率。"},
    232: {"answer": ["A", "C"], "explanation": "CC2530的两个串口USART0和USART1。"},
    233: {"answer": ["A", "B", "D"], "explanation": "串口通信方式包括单工、半双工和全双工。"},
    234: {"answer": ["B", "C", "D"], "explanation": "串口相关标志位包括UTX0IF、URX0IF等。"},
    235: {"answer": ["A", "B", "C"], "explanation": "设置波特率涉及U0BAUD和U0GCR寄存器。"},
    236: {"answer": ["A", "B", "C", "D"], "explanation": "串口通信可传输字符、字符串、数字和二进制数据。"},

    # ===== DMA 单选 (Q237-Q246) =====
    237: {"answer": ["B"], "explanation": "CC2530有5个DMA通道。"},
    238: {"answer": ["C"], "explanation": "DMA允许外设直接访问内存，无需CPU干预。"},
    239: {"answer": ["A"], "explanation": "DMA通道的优先级由通道号决定，通道0优先级最高。"},
    240: {"answer": ["D"], "explanation": "DMA传输完成后会产生中断。"},
    241: {"answer": ["B"], "explanation": "CC2530的DMA控制器支持单字节和块传输。"},
    242: {"answer": ["C"], "explanation": "DMA传输方向可以是内存到外设或外设到内存。"},
    243: {"answer": ["A"], "explanation": "DMA配置需要设置源地址和目标地址。"},
    244: {"answer": ["D"], "explanation": "DMA的触发源可以通过寄存器配置选择。"},
    245: {"answer": ["B"], "explanation": "DMA通道0的优先级最高。"},
    246: {"answer": ["C"], "explanation": "CC2530的DMA传输数据宽度可以是8位或16位。"},

    # ===== DMA 多选 (Q247-Q251) =====
    247: {"answer": ["A", "B", "C"], "explanation": "DMA传输模式包括单字节、块传输和重复模式。"},
    248: {"answer": ["A", "B", "D"], "explanation": "DMA配置需设置源地址、目标地址和传输长度。"},
    249: {"answer": ["A", "C"], "explanation": "DMA的优先级和触发源可通过寄存器配置。"},
    250: {"answer": ["B", "C", "D"], "explanation": "DMA可用于ADC数据传输、串口数据传输和内存拷贝。"},
    251: {"answer": ["A", "B", "C", "D"], "explanation": "DMA配置涉及DMAARM、DMAREQ等寄存器。"},

    # ===== ADC 单选 (Q252-Q281) =====
    252: {"answer": ["B"], "explanation": "CC2530的ADC最大转换精度是12位。"},
    253: {"answer": ["C"], "explanation": "CC2530有8个ADC模拟输入通道（AIN0~AIN7）。"},
    254: {"answer": ["A"], "explanation": "ADC转换结果=输入电压/参考电压×2^n。"},
    255: {"answer": ["D"], "explanation": "CC2530的ADC支持单次转换和连续转换。"},
    256: {"answer": ["B"], "explanation": "ADCCON1寄存器用于控制ADC的基本设置。"},
    257: {"answer": ["C"], "explanation": "ADCCON2寄存器用于控制序列转换。"},
    258: {"answer": ["A"], "explanation": "ADCCON3寄存器用于控制单次转换。"},
    259: {"answer": ["D"], "explanation": "ADC抽取率决定了转换精度和速度。"},
    260: {"answer": ["B"], "explanation": "CC2530的ADC参考电压可以选择AVDD5或内部1.25V。"},
    261: {"answer": ["C"], "explanation": "10位ADC的分辨率=参考电压/2^10。"},
    262: {"answer": ["A"], "explanation": "ADCL寄存器存放ADC转换结果的低位部分。"},
    263: {"answer": ["B"], "explanation": "ADCH寄存器存放ADC转换结果的高位部分。"},
    264: {"answer": ["D"], "explanation": "ADCCON3不设置ADC的转换方式，转换方式由ADCCON1控制。"},
    265: {"answer": ["A"], "explanation": "CC2530 ADC的模拟输入引脚需要在APCFG寄存器中配置。"},
    266: {"answer": ["B"], "explanation": "0x21=00100001，对应AIN5和AIN0。"},
    267: {"answer": ["C"], "explanation": "AIN4=bit4, AIN3=bit3, 0x10|0x08=0x18，使用|=操作。"},
    268: {"answer": ["C"], "explanation": "ADCCON3设置ADC单次转换的参考电压、抽取率和通道号。"},
    269: {"answer": ["A"], "explanation": "ADCCON3不包括转换时间的设置。"},
    270: {"answer": ["D"], "explanation": "单次转换完成后不会触发DMA请求。"},
    271: {"answer": ["D"], "explanation": "EOC位置1后，当ADCH被读取时硬件自动清除。"},
    272: {"answer": ["C"], "explanation": "EOC位不需要手动清除，读ADCH时自动清除。"},
    273: {"answer": ["A"], "explanation": "AVDD5=0x80, 256抽取率=0x20, AIN6=0x06, ADCCON3控制单次转换。"},
    274: {"answer": ["C"], "explanation": "单次转换使用ADCCON3寄存器，AVDD5=0x80, 512抽取率=0x30, AIN3=0x03。"},
    275: {"answer": ["B"], "explanation": "10位ADC参考电压5V：5V/1024≈4.89mV。"},
    276: {"answer": ["B"], "explanation": "10位ADC参考电压3.3V：3.3V/1024≈3.23mV。"},
    277: {"answer": ["D"], "explanation": "12位ADC参考电压5V，输入2V：2/5×4096≈1638.4→1638。"},
    278: {"answer": ["B"], "explanation": "10位ADC参考电压3.3V，数字量725：725/1024×3.3≈2.34V。"},
    279: {"answer": ["C"], "explanation": "电池电压监测使用AVDD5/3通道，可测量电池电压。"},
    280: {"answer": ["D"], "explanation": "12位有效数据需要抽取率512。"},
    281: {"answer": ["C"], "explanation": "抽取率128对应最多10位有效数据。"},

    # ===== ADC 单选续 (Q282-Q286) =====
    282: {"answer": ["B"], "explanation": "要使内核响应ADC中断，需要ADCIE=1（中断使能）和EA=1（总中断）。"},
    283: {"answer": ["A"], "explanation": "ADC转换精度指转换结果的位数。"},
    284: {"answer": ["D"], "explanation": "CC2530的ADC时钟源来自系统时钟。"},
    285: {"answer": ["C"], "explanation": "ADC转换时间与抽取率成正比。"},
    286: {"answer": ["B"], "explanation": "CC2530的ADC输入电压不能超过参考电压。"},

    # ===== ADC 多选 (Q287-Q296) =====
    287: {"answer": ["A", "B", "C", "D"], "explanation": "模数转换的基本流程：采样→保持→量化→编码。"},
    288: {"answer": ["B", "C", "D"], "explanation": "3.3V参考电压，小于3mV分辨率需至少10位（3.3/1024≈3.2mV）。"},
    289: {"answer": ["A", "C"], "explanation": "CC2530的ADC转换方式有单次转换和序列转换。"},
    290: {"answer": ["A", "B", "C", "D"], "explanation": "CC2530的ADC抽取率可设为64、128、256、512。"},
    291: {"answer": ["B", "D"], "explanation": "查询方式进行单次转换涉及ADCCON1和ADCCON3。"},
    292: {"answer": ["A", "B"], "explanation": "ADC单次采样结果保存在ADCL和ADCH中。"},
    293: {"answer": ["A", "B", "C", "D"], "explanation": "ADC参考电压可选AVDD5、AIN7、AIN6-AIN7差分、内部1.25V。"},
    294: {"answer": ["A", "B", "D"], "explanation": "P0_1(AIN1)、P1_0(AIN0)、P0_2(AIN2)可作为ADC输入。"},
    295: {"answer": ["B", "C", "D"], "explanation": "ADCCON3需要配置参考电压、抽取率和转换通道。"},
    296: {"answer": ["B", "D"], "explanation": "3.3V/10位≈3.2mV<15mV, 5V/10位≈4.9mV<15mV。"},

    # ===== 补充 ADC 单选 (Q297-Q315) =====
    297: {"answer": ["C"], "explanation": "CC2530的ADC支持AVDD5、AIN7、内部1.25V等多种参考电压。"},
    298: {"answer": ["D"], "explanation": "ADCL寄存器存放ADC转换结果的低位部分。"},
    299: {"answer": ["B"], "explanation": "ADCH寄存器存放ADC转换结果的高位部分。"},
    300: {"answer": ["D"], "explanation": "ADCCON3不设置ADC的转换方式。"},
    301: {"answer": ["A"], "explanation": "APCFG寄存器配置ADC的模拟输入引脚。"},
    302: {"answer": ["B"], "explanation": "0x21=00100001，对应AIN5(bit5)和AIN0(bit0)。"},
    303: {"answer": ["C"], "explanation": "AIN4=bit4, AIN3=bit3, 0x18=00011000，使用APCFG|=0x18。"},
    304: {"answer": ["C"], "explanation": "ADCCON3寄存器设置单次转换的参考电压、抽取率和通道号。"},
    305: {"answer": ["A"], "explanation": "ADCCON3不包括转换时间的设置。"},
    306: {"answer": ["D"], "explanation": "单次转换完成后不会自动触发DMA请求。"},
    307: {"answer": ["D"], "explanation": "EOC位置1后，当ADCH被读取时硬件自动清除。"},
    308: {"answer": ["C"], "explanation": "EOC位不需要手动软件清除，读ADCH时自动清除。"},
    309: {"answer": ["A"], "explanation": "AVDD5=0x80, 256抽取率=0x20, AIN6=0x06, 用|运算。"},
    310: {"answer": ["C"], "explanation": "单次转换使用ADCCON3，AVDD5=0x80, 512抽取率=0x30, AIN3=0x03。"},
    311: {"answer": ["B"], "explanation": "10位ADC参考电压5V：分辨率=5V/1024≈4.89mV。"},
    312: {"answer": ["B"], "explanation": "10位ADC参考电压3.3V：分辨率=3.3V/1024≈3.23mV。"},
    313: {"answer": ["D"], "explanation": "12位ADC参考电压5V输入2V：2/5×4096=1638.4≈1638。"},
    314: {"answer": ["B"], "explanation": "10位ADC参考电压3.3V输出725：725/1024×3.3≈2.34V。"},
    315: {"answer": ["B"], "explanation": "要使内核响应ADC中断：ADCIE=1, EA=1。"},

    # ===== ADC 多选补充 (Q316-Q325) =====
    316: {"answer": ["A", "B", "C", "D"], "explanation": "模数转换流程：采样→保持→量化→编码。"},
    317: {"answer": ["B", "C", "D"], "explanation": "3.3V参考电压，10位=3.2mV<3mV? 不满足。12位=0.8mV, 14位=0.2mV满足。"},
    318: {"answer": ["A", "C"], "explanation": "CC2530的ADC转换方式有单次转换和序列转换。"},
    319: {"answer": ["A", "B", "C", "D"], "explanation": "CC2530 ADC抽取率可设为64、128、256、512。"},
    320: {"answer": ["B", "D"], "explanation": "查询方式单次转换涉及ADCCON1（状态查询）和ADCCON3（配置转换参数）。"},
    321: {"answer": ["A", "B"], "explanation": "ADC单次采样结果保存在ADCL和ADCH中。"},
    322: {"answer": ["A", "B", "C", "D"], "explanation": "CC2530 ADC参考电压可选AVDD5、AIN7、差分电压、内部1.25V。"},
    323: {"answer": ["A", "D"], "explanation": "P0_1(AIN1)和P0_2(AIN2)可作为ADC模拟输入引脚。"},
    324: {"answer": ["B", "C", "D"], "explanation": "ADCCON3中配置参考电压、抽取率和转换通道。"},
    325: {"answer": ["B", "D"], "explanation": "3.3V/10位=3.2mV<15mV, 5V/10位=4.89mV<15mV。"},
}

# Load existing questions
q_path = Path('/Users/lujunjian/Documents/题库练习/questions.json')
questions = json.loads(q_path.read_text(encoding='utf-8'))

# Inject answers
filled = 0
for q in questions:
    qid = q['id']
    if qid in ANSWERS:
        q['answer'] = ANSWERS[qid]['answer']
        q['explanation'] = ANSWERS[qid]['explanation']
        filled += 1

# Save
q_path.write_text(json.dumps(questions, ensure_ascii=False, indent=2), encoding='utf-8')
print(f"Injected answers for {filled}/{len(questions)} questions")

# Verify
has_answer = sum(1 for q in questions if q['answer'])
print(f"Questions with answers: {has_answer}")
print(f"Questions without answers: {len(questions) - has_answer}")
