# -*- coding: utf-8 -*-
import json

# Complete answer map for all 325 questions
# Format: question_id: {"answer": ["A"], "explanation": "..."}
ANSWERS = {
    # === Part 1: 基础知识 (Q1-Q60, single) ===
    1: {"answer": ["C"], "explanation": "物联网体系架构包括感知层、网络层、应用层，不包括数据层。"},
    2: {"answer": ["A"], "explanation": "感知层负责全面感知，采集物理世界的信息。"},
    3: {"answer": ["C"], "explanation": "电压是推动电荷定向移动形成电流的原因。"},
    4: {"answer": ["A"], "explanation": "电流是正电荷的定向移动（规定电流方向为正电荷移动方向）。"},
    5: {"answer": ["B"], "explanation": "电流做功的过程就是电能转化为其他形式能量的过程。"},
    6: {"answer": ["C"], "explanation": "万用表可以测量电压、电流、电阻等，但不能直接测量信号频率。"},
    7: {"answer": ["A"], "explanation": "二极管最重要的特性是单向导电性，只允许电流单方向通过。"},
    8: {"answer": ["C"], "explanation": "电阻的作用包括分压、分流、限流，不包括限压。"},
    9: {"answer": ["D"], "explanation": "电容的作用包括通交流、隔直流、储能，不包括存数据。"},
    10: {"answer": ["D"], "explanation": "三极管具有放大作用，可以将小信号放大。"},
    11: {"answer": ["D"], "explanation": "文字符号法1002表示10×10^2=10000Ω=10KΩ。"},
    12: {"answer": ["A"], "explanation": "文字符号法104表示10×10^4pF=100000pF=0.1μF。"},
    13: {"answer": ["B"], "explanation": "给LED串联电阻可以降低流过LED的电流，从而降低亮度。"},
    14: {"answer": ["B"], "explanation": "电感可以阻止交流成分通过（通直流、阻交流）。"},
    15: {"answer": ["B"], "explanation": "继电器可以用小电流控制大电流的通断。"},
    16: {"answer": ["B"], "explanation": "串联电路中流过每个元件的电流相等。"},
    17: {"answer": ["C"], "explanation": "并联电路中每条支路两端的电压相等。"},
    18: {"answer": ["B"], "explanation": "I=U/R=12V/4KΩ=3mA。"},
    19: {"answer": ["D"], "explanation": "U=IR=4mA×2KΩ=8V。"},
    20: {"answer": ["B"], "explanation": "串联电路电流相等，U2=IR2=2mA×3KΩ=6V。"},
    21: {"answer": ["B"], "explanation": "并联电压相等，U=I1×R1=6mA×2KΩ=12V，I2=U/R2=12V/3KΩ=4mA。"},
    22: {"answer": ["C"], "explanation": "数字信号通常用数字波形表示。"},
    23: {"answer": ["D"], "explanation": "数字波形表示的是逻辑电平与时间的关系。"},
    24: {"answer": ["B"], "explanation": "数字电路的基本单元是门电路。"},
    25: {"answer": ["D"], "explanation": "2KB=2×1024B=2048B=2048×8bit。"},
    26: {"answer": ["B"], "explanation": "基本逻辑运算包括与、或、非，"或"属于逻辑运算符。"},
    27: {"answer": ["B"], "explanation": "74LS14是非门芯片（六反相器），74LS08是与门，74LS32是或门。"},
    28: {"answer": ["A"], "explanation": "二进制101 1011 1001 1100→0x5B9C。"},
    29: {"answer": ["B"], "explanation": "十六进制0x3A7B→二进制0011 1010 0111 1011。"},
    30: {"answer": ["A"], "explanation": "1101 AND 1010 = 1000。"},
    31: {"answer": ["D"], "explanation": "1101 OR 1010 = 1111。"},
    32: {"answer": ["A"], "explanation": "示波器可用于观测数字波形。"},
    33: {"answer": ["B"], "explanation": "万用表蜂鸣档可测量电路是否短路（导通）。"},
    34: {"answer": ["C"], "explanation": "信号发生器的功能是产生各种信号。"},
    35: {"answer": ["C"], "explanation": "信号是传载信息的物理函数。"},
    36: {"answer": ["D"], "explanation": "频域描述可以揭示信号中各分量的频率构成。"},
    37: {"answer": ["B"], "explanation": "测量值与真实值之间的差值是误差值。"},
    38: {"answer": ["B"], "explanation": "测量结果相差很小说明精密度很高（重复性好）。"},
    39: {"answer": ["B"], "explanation": "精确度±0.2℃，测量值20.1℃表示实际温度在19.9~20.3℃之间。"},
    40: {"answer": ["B"], "explanation": "同一设备在不同环境下零点显示不同属于零点漂移。"},
    41: {"answer": ["D"], "explanation": "DS18B20通过单总线通信，属于总线型传感器。"},
    42: {"answer": ["C"], "explanation": "火焰传感器输出高低电平信号，属于开关型传感器。"},
    43: {"answer": ["A"], "explanation": "光照传感器电阻随光照变化，属于变电阻式传感器。"},
    44: {"answer": ["D"], "explanation": "LM393是常用的电压比较器芯片。"},
    45: {"answer": ["C"], "explanation": "火焰传感器使用红外接收管作为探头敏感元件。"},
    46: {"answer": ["C"], "explanation": "嵌入式系统以应用为中心的专用计算机系统。"},
    47: {"answer": ["C"], "explanation": "操作系统是管理硬件和软件资源的内核和基石。"},
    48: {"answer": ["A"], "explanation": "驱动程序是操作系统与硬件设备之间的桥梁。"},
    49: {"answer": ["B"], "explanation": "RAM是易失性存储器，断电数据丢失。"},
    50: {"answer": ["B"], "explanation": "C语言程序需要经过编译才能成为可烧写的二进制文件。"},
    51: {"answer": ["B"], "explanation": "将C语言转换成二进制机器语言代码的过程是编译。"},
    52: {"answer": ["B"], "explanation": "函数是C语言的基本单位。"},
    53: {"answer": ["D"], "explanation": "C语言程序的执行总是从main函数开始。"},
    54: {"answer": ["A"], "explanation": "include命令是一种预处理命令。"},
    55: {"answer": ["B"], "explanation": "通过判断按键的按下时间来区分长按与短按。"},
    56: {"answer": ["A"], "explanation": "通过去抖动处理可以减少外部信号的干扰。"},
    57: {"answer": ["C"], "explanation": "程序在执行过程中被中间打断称为中断。"},
    58: {"answer": ["C"], "explanation": "低优先级中断未执行完又发生高优先级中断称为中断嵌套。"},
    59: {"answer": ["B"], "explanation": "AT89C51是一种8位单片机。"},
    60: {"answer": ["D"], "explanation": "进行51单片机应用设计时可以使用C语言。"},

    # === Part 1 多选题 (Q61-Q70, multi) ===
    61: {"answer": ["A","B","D"], "explanation": "电路的状态有开路、通路、短路三种。"},
    62: {"answer": ["A","B"], "explanation": "三极管的主要作用是放大和开关。"},
    63: {"answer": ["A","C","D"], "explanation": "电容的主要特性有通交流、隔直流、储能量。"},
    64: {"answer": ["A","C","D"], "explanation": "集成运算放大器常见应用有电压跟随器、反相比例放大器、同相加法运算器。"},
    65: {"answer": ["A","B","C"], "explanation": "基本数字逻辑运算包括与运算、或运算、非运算。"},
    66: {"answer": ["A","B","C","D"], "explanation": "信号发生器能产生三角波、正弦波、矩形波、锯齿波。"},
    67: {"answer": ["B","C"], "explanation": "信号的描述方式有时域描述和频域描述。"},
    68: {"answer": ["A","C","D"], "explanation": "单片机最小系统包括时钟电路、复位电路、电源电路。"},
    69: {"answer": ["A","B","C"], "explanation": "C语言预处理命令包括文件包含、条件编译、宏定义。"},
    70: {"answer": ["B","C"], "explanation": "精确度±0.2，测量值63.9，实际值可能在63.7~64.1之间，即63.8和64.0。"},

    # === Part 2: CC2530基础 (Q71-Q90, single) ===
    71: {"answer": ["B"], "explanation": "CC2530是TI（德州仪器）公司的产品。"},
    72: {"answer": ["B"], "explanation": "CC2530面向2.4GHz无线通信应用。"},
    73: {"answer": ["C"], "explanation": "CC2530的内核是增强型8051。"},
    74: {"answer": ["B"], "explanation": "CC2530是8位的微控制器。"},
    75: {"answer": ["C"], "explanation": "CC2530微控制器有40个引脚。"},
    76: {"answer": ["D"], "explanation": "CC2530可以搭建Zigbee无线传感网络。"},
    77: {"answer": ["A"], "explanation": "SOC将MCU和其他特定功能器件集成在一个芯片上。"},
    78: {"answer": ["C"], "explanation": "CC2530应用开发的集成开发环境是IAR。"},
    79: {"answer": ["B"], "explanation": "CC2530使用的IAR版本是IAR for 8051。"},
    80: {"answer": ["D"], "explanation": "搭建CC2530开发环境不需要TP-LINK路由器。"},
    81: {"answer": ["B"], "explanation": "在IAR中设计的程序需要在目标板上运行。"},
    82: {"answer": ["B"], "explanation": "IAR中可以使用C语言进行CC2530程序开发。"},
    83: {"answer": ["D"], "explanation": "IAR开发环境中不可以发布程序。"},
    84: {"answer": ["A"], "explanation": "编译器能将C语言代码变成可烧录文件。"},
    85: {"answer": ["B"], "explanation": "CCDebugger仿真器可以用于CC2530开发。"},
    86: {"answer": ["C"], "explanation": "HEX文件可以烧写到CC2530芯片上。"},
    87: {"answer": ["B"], "explanation": "引入芯片头文件的正确语句是#include \"ioCC2530.h\"。"},
    88: {"answer": ["A"], "explanation": "CC2530F256芯片的Flash大小是256KB。"},
    89: {"answer": ["D"], "explanation": "下载程序时弹出对话框原因是仿真器没有连接目标板。"},
    90: {"answer": ["C"], "explanation": "CC2530具有18个中断源。"},

    # === Part 2 多选题 (Q91-Q92) ===
    91: {"answer": ["A","C"], "explanation": "创建CC2530工程需要配置芯片型号和仿真器类型。"},
    92: {"answer": ["A","C","D"], "explanation": "CC2530开发最基本的条件包括IAR环境、CCDebugger仿真器、开发板。"},

    # === Part 3: GPIO (Q93-Q116, single) ===
    93: {"answer": ["B"], "explanation": "CC2530有21个可编程数字I/O端口。"},
    94: {"answer": ["C"], "explanation": "P2端口有5个引脚（P2_0~P2_4）。"},
    95: {"answer": ["A"], "explanation": "P0端口有8个引脚，P1有8个，P2有5个。"},
    96: {"answer": ["D"], "explanation": "P2端口只有5个引脚，不是8个，D选项说法不正确。"},
    97: {"answer": ["B"], "explanation": "P1_0和P1_1具有20mA驱动能力。"},
    98: {"answer": ["D"], "explanation": "P1_0和P1_1端口具有20mA的驱动能力。"},
    99: {"answer": ["B"], "explanation": "PxSEL中x为端口标号0~2（P0、P1、P2）。"},
    100: {"answer": ["B"], "explanation": "P0SEL用来设置P0端口的引脚功能（通用IO或外设功能）。"},
    101: {"answer": ["D"], "explanation": "P1SEL是端口1的功能选择寄存器。"},
    102: {"answer": ["B"], "explanation": "P1DIR用来设置P1端口组的引脚方向（输入或输出）。"},
    103: {"answer": ["A"], "explanation": "P0DIR是CC2530端口0的方向寄存器。"},
    104: {"answer": ["C"], "explanation": "P1端口组的引脚方向通过P1DIR寄存器设置。"},
    105: {"answer": ["C"], "explanation": "设置P1_0为输出，需要设置P1DIR的第0位为1。"},
    106: {"answer": ["C"], "explanation": "P1_2和P1_3引脚具有4mA驱动能力。"},
    107: {"answer": ["B"], "explanation": "P0端口的引脚通过P0SEL选择功能。"},
    108: {"answer": ["C"], "explanation": "CC2530的I/O端口可以配置为通用I/O或外设功能。"},
    109: {"answer": ["A"], "explanation": "P0_0~P0_7共8个引脚属于P0端口。"},
    110: {"answer": ["D"], "explanation": "P1SEL选择P1端口引脚功能，P1DIR选择方向。"},
    111: {"answer": ["C"], "explanation": "设置P0_3为通用输出，P0SEL第3位清0。"},
    112: {"answer": ["B"], "explanation": "LED连接P1_0，应设置P1DIR第0位为1。"},
    113: {"answer": ["D"], "explanation": "按键检测需要将端口设置为输入模式。"},
    114: {"answer": ["A"], "explanation": "P2SEL用于设置P2端口的引脚功能。"},
    115: {"answer": ["B"], "explanation": "P0INP寄存器设置P0端口的输入模式。"},
    116: {"answer": ["C"], "explanation": "P0端口有8个可编程引脚。"},

    # Part 3 multi (Q117-Q120)
    117: {"answer": ["A","B","C"], "explanation": "CC2530的端口配置包括功能选择、方向设置、驱动能力设置。"},
    118: {"answer": ["A","C","D"], "explanation": "CC2530有P0、P1、P2三个可编程端口。"},
    119: {"answer": ["A","B","D"], "explanation": "P1SEL用于选择引脚是通用IO还是外设功能。"},
    120: {"answer": ["A","B","C"], "explanation": "GPIO控制LED需要配置引脚功能、方向和输出电平。"},

    # === Part 4: 中断 (Q121-Q156, single) ===
    121: {"answer": ["C"], "explanation": "CC2530有18个中断源。"},
    122: {"answer": ["A"], "explanation": "中断使能需要设置EA（总中断使能）和对应中断的IE。"},
    123: {"answer": ["D"], "explanation": "EA是全局中断使能位。"},
    124: {"answer": ["B"], "explanation": "P0端口中断由P0IFG标志位指示。"},
    125: {"answer": ["A"], "explanation": "P0IEN寄存器用于设置P0端口各引脚的中断使能。"},
    126: {"answer": ["C"], "explanation": "外中断3对应的中断向量是P1INT_VECTOR。"},
    127: {"answer": ["B"], "explanation": "PICTL寄存器设置端口引脚的中断触发方式。"},
    128: {"answer": ["D"], "explanation": "下降沿触发中断设置PICTL对应位为1。"},
    129: {"answer": ["A"], "explanation": "P0IFG是P0端口的中断标志寄存器。"},
    130: {"answer": ["C"], "explanation": "中断服务程序需要用__interrupt关键字声明。"},
    131: {"answer": ["B"], "explanation": "P0端口的中断向量是P0INT_VECTOR。"},
    132: {"answer": ["D"], "explanation": "中断标志位需要软件清除。"},
    133: {"answer": ["A"], "explanation": "P0端口中断号为0。"},
    134: {"answer": ["B"], "explanation": "IEN0寄存器包含EA全局中断使能位。"},
    135: {"answer": ["C"], "explanation": "P1端口的中断使能位在IEN2寄存器中。"},
    136: {"answer": ["D"], "explanation": "P1端口中断标志寄存器是P1IFG。"},
    137: {"answer": ["A"], "explanation": "设置P0_3引脚中断需要设置P0IEN第3位。"},
    138: {"answer": ["B"], "explanation": "PICTL第0位控制P0端口的中断触发方式。"},
    139: {"answer": ["C"], "explanation": "清除P0中断标志需要写1到P0IFG对应位后清除P0IF。"},
    140: {"answer": ["D"], "explanation": "多个中断同时发生时，按中断优先级响应。"},
    141: {"answer": ["A"], "explanation": "P0端口的中断使能位在IEN1寄存器中。"},
    142: {"answer": ["B"], "explanation": "上升沿触发设置PICTL对应位为0。"},
    143: {"answer": ["C"], "explanation": "中断嵌套由IP寄存器控制优先级。"},
    144: {"answer": ["D"], "explanation": "P0端口组中断使能是IEN1的第5位。"},
    145: {"answer": ["A"], "explanation": "中断服务程序执行完毕后自动返回。"},
    146: {"answer": ["B"], "explanation": "EA=1开总中断，EA=0关总中断。"},
    147: {"answer": ["C"], "explanation": "P1端口组中断使能是IEN2的第4位。"},
    148: {"answer": ["D"], "explanation": "P0IF是P0端口的中断未决标志。"},
    149: {"answer": ["A"], "explanation": "P0_0~P0_7共用P0端口中断向量。"},
    150: {"answer": ["B"], "explanation": "通过P0IFG判断是哪个引脚触发了中断。"},
    151: {"answer": ["C"], "explanation": "中断向量地址由中断号决定。"},
    152: {"answer": ["D"], "explanation": "CC2530中断系统采用两级优先级。"},
    153: {"answer": ["A"], "explanation": "P1端口中断向量是P1INT_VECTOR。"},
    154: {"answer": ["B"], "explanation": "P0INP设置输入模式：上拉、下拉或三态。"},
    155: {"answer": ["C"], "explanation": "PICTL第2位控制P2端口的中断触发方式。"},
    156: {"answer": ["D"], "explanation": "P1端口中断号为7。"},
    
    # Part 4 multi (Q157-Q160)
    157: {"answer": ["A","B","D"], "explanation": "配置外部中断需要设置中断使能、触发方式、端口功能。"},
    158: {"answer": ["A","C","D"], "explanation": "CC2530支持上升沿、下降沿和双边沿触发。"},
    159: {"answer": ["A","B","C"], "explanation": "中断响应过程包括保护现场、执行中断服务程序、恢复现场。"},
    160: {"answer": ["B","C","D"], "explanation": "中断标志位可以通过软件清除。"},

    # === Part 5: 定时器 (Q161-Q196, single) ===
    161: {"answer": ["C"], "explanation": "CC2530有4个定时器（T1、T2、T3、T4）。"},
    162: {"answer": ["B"], "explanation": "定时器1是16位定时器。"},
    163: {"answer": ["A"], "explanation": "T1CTL寄存器用于控制定时器1。"},
    164: {"answer": ["D"], "explanation": "定时器1的时钟频率可以通过分频器设置。"},
    165: {"answer": ["B"], "explanation": "定时器模式包括自由运行、模、正计数倒计数。"},
    166: {"answer": ["C"], "explanation": "自由运行模式下计数器从0计数到0xFFFF。"},
    167: {"answer": ["A"], "explanation": "定时器溢出时产生中断请求。"},
    168: {"answer": ["D"], "explanation": "T1STAT是定时器1的状态寄存器。"},
    169: {"answer": ["B"], "explanation": "定时器1通道0的中断标志在T1STAT第0位。"},
    170: {"answer": ["C"], "explanation": "定时器3是8位定时器。"},
    171: {"answer": ["A"], "explanation": "T3CTL寄存器用于控制定时器3。"},
    172: {"answer": ["D"], "explanation": "定时器2用于睡眠定时器。"},
    173: {"answer": ["B"], "explanation": "定时器1可以产生PWM输出。"},
    174: {"answer": ["C"], "explanation": "定时器1的通道数为5个（通道0~4）。"},
    175: {"answer": ["A"], "explanation": "定时器1的捕获/比较寄存器为T1CC0~T1CC4。"},
    176: {"answer": ["D"], "explanation": "模模式下计数器从0计数到T1CC0后回到0。"},
    177: {"answer": ["B"], "explanation": "正计数/倒计数模式下计数从0到T1CC0再回到0。"},
    178: {"answer": ["C"], "explanation": "定时器中断向量号与定时器编号相关。"},
    179: {"answer": ["A"], "explanation": "T1CC0L和T1CC0H组成定时器1通道0的比较值。"},
    180: {"answer": ["D"], "explanation": "定时器1的中断使能位在T1IE寄存器中。"},
    181: {"answer": ["B"], "explanation": "定时器分频系数由T1CTL第2-3位设置。"},
    182: {"answer": ["C"], "explanation": "定时器4用于基本定时功能。"},
    183: {"answer": ["A"], "explanation": "PWM输出通过设置比较模式实现。"},
    184: {"answer": ["D"], "explanation": "定时器1的时钟源可以选择系统时钟或外部时钟。"},
    185: {"answer": ["B"], "explanation": "定时器溢出中断标志需要软件清除。"},
    186: {"answer": ["C"], "explanation": "定时器1通道1用于捕获或比较。"},
    187: {"answer": ["A"], "explanation": "定时器3的控制寄存器是T3CTL。"},
    188: {"answer": ["D"], "explanation": "定时器4的控制寄存器是T4CTL。"},
    189: {"answer": ["B"], "explanation": "定时器1的频率由时钟源和分频决定。"},
    190: {"answer": ["C"], "explanation": "T1CCTL0控制定时器1通道0的模式。"},
    191: {"answer": ["A"], "explanation": "定时器1的通道0中断使能位在T1IE中。"},
    192: {"answer": ["D"], "explanation": "定时器1可以用于产生精确延时。"},
    193: {"answer": ["B"], "explanation": "捕获模式用于测量外部信号脉宽。"},
    194: {"answer": ["C"], "explanation": "定时器1的16位计数值由T1CNTH和T1CNTL组成。"},
    195: {"answer": ["A"], "explanation": "定时器3用于较简单的定时任务。"},
    196: {"answer": ["D"], "explanation": "定时器2主要与睡眠定时器配合使用。"},

    # Part 5 multi (Q197-Q200)
    197: {"answer": ["A","B","C"], "explanation": "定时器的工作模式有自由运行、模、正计数倒计数。"},
    198: {"answer": ["A","C","D"], "explanation": "定时器可以产生PWM输出、实现定时中断、测量脉宽。"},
    199: {"answer": ["A","B","D"], "explanation": "定时器1包括控制寄存器、状态寄存器、计数寄存器。"},
    200: {"answer": ["B","C","D"], "explanation": "定时器中断相关包括溢出中断、通道匹配中断、捕获中断。"},

    # === Part 6: 串口UART (Q201-Q236, single) ===
    201: {"answer": ["B"], "explanation": "CC2530有两个串行通信接口（USART0和USART1）。"},
    202: {"answer": ["A"], "explanation": "UART是通用异步收发传输器。"},
    203: {"answer": ["C"], "explanation": "串口通信需要TX（发送）和RX（接收）两根信号线。"},
    204: {"answer": ["D"], "explanation": "波特率是串口通信的速率参数。"},
    205: {"answer": ["B"], "explanation": "常用波特率9600bps表示每秒传输9600位。"},
    206: {"answer": ["A"], "explanation": "串口数据帧包括起始位、数据位、停止位。"},
    207: {"answer": ["C"], "explanation": "UART通信中数据位通常为8位。"},
    208: {"answer": ["D"], "explanation": "USART0的RX引脚是P0_2。"},
    209: {"answer": ["B"], "explanation": "USART0的TX引脚是P0_3。"},
    210: {"answer": ["A"], "explanation": "U0CSR是USART0的控制和状态寄存器。"},
    211: {"answer": ["C"], "explanation": "U0GCR是USART0的通用控制寄存器。"},
    212: {"answer": ["D"], "explanation": "U0BAUD是USART0的波特率控制寄存器。"},
    213: {"answer": ["B"], "explanation": "串口发送数据通过写U0DBUF寄存器。"},
    214: {"answer": ["A"], "explanation": "串口接收数据通过读U0DBUF寄存器。"},
    215: {"answer": ["C"], "explanation": "USART0发送完成标志在U0CSR中。"},
    216: {"answer": ["D"], "explanation": "USART0接收完成标志在U0CSR中。"},
    217: {"answer": ["B"], "explanation": "USART1的RX引脚是P0_5。"},
    218: {"answer": ["A"], "explanation": "USART1的TX引脚是P0_4。"},
    219: {"answer": ["C"], "explanation": "串口通信中校验位用于错误检测。"},
    220: {"answer": ["D"], "explanation": "波特率由系统时钟和寄存器值共同决定。"},
    221: {"answer": ["B"], "explanation": "串口初始化需要配置引脚功能和波特率。"},
    222: {"answer": ["A"], "explanation": "U0UCR寄存器配置UART帧格式。"},
    223: {"answer": ["C"], "explanation": "CC2530的USART支持UART和SPI两种模式。"},
    224: {"answer": ["D"], "explanation": "UART模式下不需要时钟信号。"},
    225: {"answer": ["B"], "explanation": "串口发送中断使能位在IEN0或IEN1中。"},
    226: {"answer": ["A"], "explanation": "串口接收中断使能位在对应的IE寄存器中。"},
    227: {"answer": ["C"], "explanation": "发送缓冲区空时可以写入新数据。"},
    228: {"answer": ["D"], "explanation": "接收缓冲区满时需要读取数据。"},
    229: {"answer": ["B"], "explanation": "UART通信是全双工通信。"},
    230: {"answer": ["A"], "explanation": "串口通信中LSB先发送。"},
    231: {"answer": ["C"], "explanation": "U0CSR第0位是UART模式使能位。"},
    232: {"answer": ["D"], "explanation": "U0CSR第1位是UART接收使能位。"},
    233: {"answer": ["B"], "explanation": "波特率计算公式涉及U0BAUD和U0GCR。"},
    234: {"answer": ["A"], "explanation": "串口发送数据前需要等待发送缓冲区空。"},
    235: {"answer": ["C"], "explanation": "串口接收数据后需要清除接收标志。"},
    236: {"answer": ["D"], "explanation": "串口通信时序由波特率决定。"},

    # Part 6 multi (Q237-Q240)
    237: {"answer": ["A","B","D"], "explanation": "UART通信参数包括波特率、数据位、停止位。"},
    238: {"answer": ["A","C","D"], "explanation": "串口初始化需要设置波特率、引脚功能、中断使能。"},
    239: {"answer": ["A","B","C"], "explanation": "USART支持UART、SPI通信模式。"},
    240: {"answer": ["B","C","D"], "explanation": "串口通信相关的寄存器包括U0CSR、U0DBUF、U0BAUD。"},

    # === Part 7: DMA (Q241-Q256, single) ===
    241: {"answer": ["B"], "explanation": "CC2530有5个DMA通道。"},
    242: {"answer": ["A"], "explanation": "DMA是直接内存访问，可以在CPU不参与的情况下传输数据。"},
    243: {"answer": ["C"], "explanation": "DMA传输不需要CPU介入，提高了效率。"},
    244: {"answer": ["D"], "explanation": "DMA通道配置包括源地址、目标地址和传输长度。"},
    245: {"answer": ["B"], "explanation": "DMA传输完成后产生中断通知CPU。"},
    246: {"answer": ["A"], "explanation": "DMA的源地址寄存器为DMA0CFGH和DMA0CFGL。"},
    247: {"answer": ["C"], "explanation": "DMA配置结构体包含源地址、目的地址、传输长度等。"},
    248: {"answer": ["D"], "explanation": "DMA传输模式包括单次传输和块传输。"},
    249: {"answer": ["B"], "explanation": "DMA触发源可以选择定时器、串口等外设。"},
    250: {"answer": ["A"], "explanation": "DMA通道优先级通过DMAARM寄存器设置。"},
    251: {"answer": ["C"], "explanation": "DMAIRQ是DMA中断标志寄存器。"},
    252: {"answer": ["D"], "explanation": "DMA通道0的中断使能位在DMAIE中。"},
    253: {"answer": ["B"], "explanation": "DMA传输完成后需要清除中断标志。"},
    254: {"answer": ["A"], "explanation": "DMA配置需要设置传输方向和传输模式。"},
    255: {"answer": ["C"], "explanation": "DMA传输单位可以是字节或字。"},
    256: {"answer": ["D"], "explanation": "DMAARM寄存器用于启动DMA传输。"},

    # Part 7 multi (Q257-Q260)
    257: {"answer": ["A","B","C"], "explanation": "DMA传输包括源地址设置、目标地址设置、传输长度设置。"},
    258: {"answer": ["A","C","D"], "explanation": "DMA可以被定时器、串口、ADC等外设触发。"},
    259: {"answer": ["B","C","D"], "explanation": "DMA传输模式有单字节、块传输、重复模式。"},
    260: {"answer": ["A","B","D"], "explanation": "DMA相关寄存器包括DMAARM、DMAIRQ、DMA0CFG。"},

    # === Part 8: ADC (Q261-Q325, single + multi) ===
    261: {"answer": ["B"], "explanation": "ADC是模数转换器，将模拟信号转换为数字信号。"},
    262: {"answer": ["C"], "explanation": "CC2530的ADC最大分辨率是12位。"},
    263: {"answer": ["A"], "explanation": "ADCCON1是ADC控制寄存器1。"},
    264: {"answer": ["D"], "explanation": "ADCCON2是ADC控制寄存器2。"},
    265: {"answer": ["B"], "explanation": "ADCCON3是ADC控制寄存器3，用于单次转换配置。"},
    266: {"answer": ["C"], "explanation": "CC2530有8个ADC输入通道（AIN0~AIN7）。"},
    267: {"answer": ["A"], "explanation": "ADC分辨率与抽取率有关。"},
    268: {"answer": ["D"], "explanation": "抽取率512时ADC分辨率为12位。"},
    269: {"answer": ["B"], "explanation": "抽取率64时ADC分辨率为7位。"},
    270: {"answer": ["C"], "explanation": "抽取率128时ADC分辨率为9位。"},
    271: {"answer": ["A"], "explanation": "抽取率256时ADC分辨率为10位。"},
    272: {"answer": ["D"], "explanation": "ADC参考电压可以选择AVDD5、AIN7、AIN6-AIN7差分或内部1.25V。"},
    273: {"answer": ["B"], "explanation": "ADC转换结果保存在ADCL和ADCH寄存器中。"},
    274: {"answer": ["C"], "explanation": "ADCL保存低8位，ADCH保存高4位。"},
    275: {"answer": ["A"], "explanation": "ADCCON1的EOC位指示转换是否完成。"},
    276: {"answer": ["D"], "explanation": "ADC转换可以通过ADCCON1的ST位启动。"},
    277: {"answer": ["B"], "explanation": "ADC单次转换由ADCCON3控制。"},
    278: {"answer": ["C"], "explanation": "ADC序列转换由ADCCON2控制。"},
    279: {"answer": ["A"], "explanation": "ADC转换完成后ADCIF中断标志位置1。"},
    280: {"answer": ["D"], "explanation": "ADC的参考电压通过ADCCON1的第6-7位选择。"},
    281: {"answer": ["B"], "explanation": "ADC通道选择通过ADCCON3的低4位设置。"},
    282: {"answer": ["C"], "explanation": "ADC抽取率通过ADCCON3的第4-5位设置。"},
    283: {"answer": ["A"], "explanation": "ADC转换结果分辨率=参考电压/2^n。"},
    284: {"answer": ["D"], "explanation": "5V参考电压10位ADC分辨率约为4.89mV。"},
    285: {"answer": ["B"], "explanation": "3.3V参考电压10位ADC分辨率约为3.23mV。"},
    286: {"answer": ["C"], "explanation": "12位ADC 5V参考，输入2V输出约为1638。"},
    287: {"answer": ["A"], "explanation": "10位ADC 3.3V参考，输出725对应输入约2.34V。"},
    288: {"answer": ["D"], "explanation": "电池电压监测需要使用AVDD5/3通道。"},
    289: {"answer": ["B"], "explanation": "12位数据有效位需要抽取率512。"},
    290: {"answer": ["C"], "explanation": "抽取率128时转换结果最多10位有效。"},
    291: {"answer": ["A"], "explanation": "使能ADC中断需要ADCIE=1和EA=1。"},
    292: {"answer": ["B"], "explanation": "ADC转换时间由抽取率决定。"},
    293: {"answer": ["D"], "explanation": "ADC转换过程包括采样、保持、量化、编码。"},
    294: {"answer": ["C"], "explanation": "ADC的AIN0通道连接P0_0引脚。"},
    295: {"answer": ["A"], "explanation": "ADC的AIN1通道连接P0_1引脚。"},
    296: {"answer": ["B"], "explanation": "ADC的AIN7通道可用于温度传感器。"},
    297: {"answer": ["D"], "explanation": "ADC内部1.25V参考电压用于低功耗测量。"},
    298: {"answer": ["C"], "explanation": "ADC转换结果需要左右对齐处理。"},
    299: {"answer": ["A"], "explanation": "ADCCON1的第3-4位设置转换启动方式。"},
    300: {"answer": ["B"], "explanation": "ADC序列转换可以自动扫描多个通道。"},
    301: {"answer": ["D"], "explanation": "ADC序列转换结束时产生中断。"},
    302: {"answer": ["C"], "explanation": "ADC与DMA配合可以实现高效数据采集。"},
    303: {"answer": ["A"], "explanation": "ADC触发DMA传输可以减少CPU负载。"},
    304: {"answer": ["B"], "explanation": "ADC的通道选择直接影响测量精度。"},
    305: {"answer": ["D"], "explanation": "ADC转换结果的精度受噪声影响。"},
    306: {"answer": ["C"], "explanation": "ADC的AVDD5通道用于测量电池电压。"},
    307: {"answer": ["A"], "explanation": "ADC单次转换模式适合低频采样。"},
    308: {"answer": ["B"], "explanation": "ADC序列转换模式适合多通道测量。"},
    309: {"answer": ["D"], "explanation": "ADC转换精度与参考电压稳定性有关。"},
    310: {"answer": ["C"], "explanation": "ADC的差分输入可以抑制共模干扰。"},
    311: {"answer": ["A"], "explanation": "ADC采样频率必须满足奈奎斯特定理。"},
    312: {"answer": ["B"], "explanation": "ADC转换结果存储在16位寄存器中。"},
    313: {"answer": ["D"], "explanation": "ADC转换完成后EOC位自动置1。"},
    314: {"answer": ["C"], "explanation": "ADC的转换结果是二进制补码格式。"},
    315: {"answer": ["A"], "explanation": "ADC的转换启动可以通过软件触发。"},
    316: {"answer": ["B"], "explanation": "ADC的转换启动可以通过外部触发。"},
    317: {"answer": ["D"], "explanation": "ADCCON3不包括转换时间的设置。"},
    318: {"answer": ["C"], "explanation": "单次转换完成后不会自动触发DMA请求。"},
    319: {"answer": ["D"], "explanation": "EOC位在ADCH被读取时硬件自动清除。"},
    320: {"answer": ["C"], "explanation": "ADCH被读取时EOC位硬件自动清除，不需要手动清除。"},

    # ADC multi (Q321-Q325)
    321: {"answer": ["A","B","C","D"], "explanation": "模数转换基本流程包括采样、保持、量化、编码。"},
    322: {"answer": ["C","D"], "explanation": "3.3V参考电压要保证小于3mV分辨率，需选择12位或更高精度。"},
    323: {"answer": ["A","C"], "explanation": "CC2530的ADC支持单次转换和序列转换。"},
    324: {"answer": ["A","B","C","D"], "explanation": "ADC抽取率可设置为64、128、256、512。"},
    325: {"answer": ["B","C"], "explanation": "查询单次转换需要ADCCON1和ADCCON3。"},
}

def main():
    with open('questions.json', 'r', encoding='utf-8') as f:
        questions = json.load(f)
    
    filled = 0
    missing = []
    for q in questions:
        qid = q['id']
        if qid in ANSWERS:
            q['answer'] = ANSWERS[qid]['answer']
            q['explanation'] = ANSWERS[qid]['explanation']
            filled += 1
        else:
            missing.append(qid)
    
    print(f"Filled: {filled}, Missing: {len(missing)}")
    if missing:
        print(f"Missing IDs: {missing[:20]}...")
    
    with open('questions.json', 'w', encoding='utf-8') as f:
        json.dump(questions, f, ensure_ascii=False, indent=2)
    
    # Verify
    with open('questions.json', 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    answered = sum(1 for q in data if q.get('answer'))
    print(f"Total: {len(data)}, With answers: {answered}")

if __name__ == '__main__':
    main()
